application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      milo-fg:
        license: Apache-2.0
        inputs:
          fgSite: $FG_SITE
          fgClientId: $FG_CLIENT_ID
          fgAuthority: $FG_AUTHORITY
          shareUrl: $SHARE_URL
          fgShareUrl: $FG_SHARE_URL
          rootFolder: $ROOT_FOLDER
          fgRootFolder: $FG_ROOT_FOLDER
          skipInProgressCheck: $SKIP_INPROGRESS_CHECK
          clientId: $CLIENT_ID
          tenantId: $TENANT_ID
          certPassword: $CERT_PASSWORD
          certKey: $CERT_KEY
          certThumbprint: $CERT_THUMB_PRINT
          batchFilesPath: $BATCH_FILES_PATH
          numBatchFiles: $NUM_BATCH_FILES
          numBulkPerBatch: $NUM_BULK_PER_BATCH
        actions:
          copy:
            function: actions/copy/copy.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          copy-worker:
            function: actions/copy/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 2048
          promote:
            function: actions/promote/promote.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
          promote-batch:
            function: actions/promote/promoteBatch.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 1900000
          promote-worker:
            function: actions/promote/worker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
              memorySize: 1024
              concurrency: 5
          promote-tracker:
            function: actions/promote/tracker.js
            web: 'no'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
            limits:
              timeout: 3600000
          status:
            function: actions/status/status.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              LOG_LEVEL: debug
