name: AIO App - Stage Deploy

on:
  push:
    branches:
      - stage
jobs:
  deploy:
    name: Deploy to Stage
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['20']
        os: [ubuntu-latest]
    steps:
      - name: Check Repo Variables
        run: |
          echo "GROUP_CHECK_URL : $GROUP_CHECK_URL"
          echo "FG_USER_GROUPS : $FG_USER_GROUPS"
          echo "FG_ADMIN_GROUPS : $FG_ADMIN_GROUPS"
          echo "BATCH_FILES_PATH : $BATCH_FILES_PATH"
          echo "MAX_FILES_PER_BATCH : $MAX_FILES_PER_BATCH"
          echo "NUM_BULK_REQUEST : $NUM_BULK_REQUEST"
          echo "FG_DIR_PATTERN : $FG_DIR_PATTERN"
          echo "SITE_ROOT_PATH_REX : $SITE_ROOT_PATH_REX"
          echo "BULK_PREVIEW_CHECK_INTERVAL : $BULK_PREVIEW_CHECK_INTERVAL"
          echo "MAX_BULK_PREVIEW_CHECKS : $MAX_BULK_PREVIEW_CHECKS"
          echo "ENABLE_PREVEW_PUBLISH : $ENABLE_PREVEW_PUBLISH"
        env:
          GROUP_CHECK_URL: ${{ vars.GROUP_CHECK_URL }}
          FG_USER_GROUPS: ${{ vars.FG_USER_GROUPS }}
          FG_ADMIN_GROUPS: ${{ vars.FG_ADMIN_GROUPS }}
          BATCH_FILES_PATH: ${{ vars.BATCH_FILES_PATH }}
          MAX_FILES_PER_BATCH: ${{ vars.MAX_FILES_PER_BATCH }}
          NUM_BULK_REQUEST: ${{ vars.NUM_BULK_REQUEST }}
          FG_DIR_PATTERN: ${{ vars.FG_DIR_PATTERN }}
          SITE_ROOT_PATH_REX: ${{ vars.SITE_ROOT_PATH_REX }}
          BULK_PREVIEW_CHECK_INTERVAL: ${{ vars.BULK_PREVIEW_CHECK_INTERVAL }}
          MAX_BULK_PREVIEW_CHECKS: ${{ vars.MAX_BULK_PREVIEW_CHECKS }}
          ENABLE_PREVEW_PUBLISH: ${{ vars.ENABLE_PREVEW_PUBLISH }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ${{ matrix.os }}
          version: 10.x.x
      - name: Build
        env:
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_PROD }}
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: build
      - name: Deploy
        env:
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_STAGE }}
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_STAGE }}
          FG_SITE: ${{ secrets.FG_SITE }}
          FG_CLIENT_ID: ${{ secrets.FG_CLIENT_ID }}
          FG_AUTHORITY: ${{ secrets.FG_AUTHORITY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          CERT_KEY: ${{ secrets.CERT_KEY }}
          CERT_THUMB_PRINT: ${{ secrets.CERT_THUMB_PRINT }}
          HELIX_ADMIN_API_KEYS: ${{ secrets.HELIX_ADMIN_API_KEYS }}
          SPLUNK_HEC__HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN_STAGE }}
          GROUP_CHECK_URL: ${{ vars.GROUP_CHECK_URL }}
          FG_USER_GROUPS: ${{ vars.FG_USER_GROUPS }}
          FG_ADMIN_GROUPS: ${{ vars.FG_ADMIN_GROUPS }}
          BATCH_FILES_PATH: ${{ vars.BATCH_FILES_PATH }}
          MAX_FILES_PER_BATCH: ${{ vars.MAX_FILES_PER_BATCH }}
          NUM_BULK_REQUEST: ${{ vars.NUM_BULK_REQUEST }}
          FG_DIR_PATTERN: ${{ vars.FG_DIR_PATTERN }}
          SITE_ROOT_PATH_REX: ${{ vars.SITE_ROOT_PATH_REX }}
          BULK_PREVIEW_CHECK_INTERVAL: ${{ vars.BULK_PREVIEW_CHECK_INTERVAL }}
          MAX_BULK_PREVIEW_CHECKS: ${{ vars.MAX_BULK_PREVIEW_CHECKS }}
          ENABLE_PREVEW_PUBLISH: ${{ vars.ENABLE_PREVEW_PUBLISH }}
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: deploy
          noPublish: true
